version: 2 # use CircleCI 2.0
jobs: # basic units of work in a run
  deploy:
    machine:
        enabled: true
    steps:
      - checkout
      - run:
          name: Deploy Over SSH
          command: |
            scp -r payloads $SSH_USER@$SSH_HOST:$SSH_PATH
            scp -r deploy $SSH_USER@$SSH_HOST:$SSH_PATH
            scp -r health $SSH_USER@$SSH_HOST:$SSH_PATH

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master

