version: 2 # use CircleCI 2.0
jobs: # basic units of work in a run
  deploy1:
    machine:
        enabled: true
    steps:
      - checkout
      - run:
          name: Deploy Over SSH
          command: |
            scp -r health $SSH_USER@$SSH_HOST:$SSH_PATH
  deploy2:
    machine:
        enabled: true
    steps:
      - checkout
      - run:
          name: Deploy Over SSH
          command: |
            scp -r payloads $SSH_USER2@$SSH_HOST2:$SSH_PATH2
            scp -r deploy $SSH_USER2@$SSH_HOST2:$SSH_PATH2

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy1:
          filters:
            branches:
              only: master
      - deploy2:
          filters:
            branches:
              only: master

